services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_DISTRO=$ROS_DISTRO
    command: bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && exec bash"
    working_dir: ${PWD}
    volumes:
      - ./:${PWD}
      - /dev:/dev
      - /tmp:/tmp
      - /var/log/journal:/var/log/journal
      - ${XAUTHORITY}:/home/user/.Xauthority:ro
    environment:
      # Application
      - DATA_PATH=${PWD}/data
      # Graphics
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      #- NVIDIA_DRIVER_CAPABILITIES=all
      # ROS 2
      - COLCON_HOME=${PWD}/.colcon
      - ROS_DOMAIN_ID=0
      # Other
      - HISTFILE=${PWD}/.bash_history
    devices:
      - /dev/dri:/dev/dri  # Allow access to GPU devices if needed
    #runtime: nvidia
    network_mode: host
    privileged: true
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ulimits:
      core: 0
    shm_size: 256m

